### PR TITLE
Display 404 Not found pages in the locale prefix language

### LINKED ISSUE #19: Translation issues on 404 (not found) route
**Describe the bug**
When reaching a route which does not exist while using a specific language prefix (example: `/en/fake-route`) the route will not be displayed in english (URL prefix language) but in default language.

**To Reproduce**
1. Go to any route that doesn't exist in your Gridsome app, with a language prefix at the beginning of the path
2. The route should be in the prefix language, it's not, it's in the default language which was configured in gridsome-i18n instead.

In `gridsome.client.js`, when entering this kind of non-existing route, in `beforeEach` hook, the value of `to.meta.locale` is always the default language, the prefix is not taken into account => the route is in default language.

**Expected behavior**
The 404 route and template is in the language specified as prefix in the URL.

I haven't found a workaround yet, which is a problem because when a user reaches a non-existing page somehow, it will be shown an error page in French instead of its own language (say, English).

### PR DESCRIPTION
**Pull request by cfecherolle**
Fixes #19 
Solution is courtesy of @daaru00!

I have done some local testing on my own app, but it might need to be tested a little bit more for side-effects and such?

Sorry for the formatting fixes included in this commit, my IDE insists on making them when I save.
If it's a bother, I can change the settings of my software: just tell me!

### CODE REVIEW

**Comment by daaru00** [comment]
> Sorry for the formatting fixes included in this commit, my IDE insists on making them when I save.
> If it's a bother, I can change the settings of my software: just tell me!

naa, no problem! My fault, the codebase does not contain an eslint configuration and/or .editorconfig file. I'll add them in another branch so as to test that it works properly :+1: 

About this PR, I tested with a new Gridsome project and I receiving an error:
```
Error: Could not find component /sandbox/src/pages/404.vue.
    at Pages._parseComponent (/sandbox/node_modules/gridsome/lib/pages/pages.js:415:13)
    at Pages._createRouteOptions (/sandbox/node_modules/gridsome/lib/pages/pages.js:310:32)
    at Pages.createRoute (/sandbox/node_modules/gridsome/lib/pages/pages.js:106:26)
    at Pages.createPage (/sandbox/node_modules/gridsome/lib/pages/pages.js:171:24)
    at createPage (/sandbox/node_modules/gridsome/lib/app/actions.js:260:24)
    at VueI18n.createManagedPages (/sandbox/node_modules/gridsome-plugin-i18n/gridsome.server.js:55:6)
    at Plugins.run (/sandbox/node_modules/gridsome/lib/app/Plugins.js:141:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
this because the `pages/404.vue` is not mandatory and if user did not create a custom 404 page the specified component cannot be found (and I am not convinced that it is correct to hardcode the path).

I would like to propose an improvement: what about getting current 404 page data (and related route object) to extrapolate the component name, letting core to check if the component is there or not?

Doing some tests I can suggest to use:
```js
const page = this.pages.findPage({ path: '/404' })
// page could be null if not found
```
to find the correct page and:
```js
const route = this.pages.getRoute(page.internal.route)
```
to find the related route. 

This because "page" object does not contain the component path instead the "route" one does:
```js
console.log(route.component)
```
this will print `/my/project/path/node_modules/gridsome/app/pages/404.vue` if custom 404 page does not exist and `/my/project/path/src/pages/404.vue` if exist. (realized that works also with _404.vue).

If you want to test it I create a CodeSandbox with some use case: https://codesandbox.io/s/gridsome-plugin-i18n-fix404translation-gdq9v feel free to fork it and edit based on what you need.

**Comment by cfecherolle** [comment]
Thanks @daaru00!
I forgot this use case, so I added the new code and pushed another commit.

I tried with and without `404.vue` defined and it seems to be fine on my side!
Can you try it too when you have some time? Thank you!

**Review by daaru00 — APPROVED** [review]
Hi @cfecherolle,

seems working as expected, I didn't found any issue when testing. Do a version bump and let's merge it :tada:

**Comment by cfecherolle** [comment]
I merged the PR, but I don't have the rights to push on master to add the version bump, and I should have done it in this PR before merging. Sorry about that.

**Comment by daaru00** [comment]
No problem @cfecherolle! Branch merged and version deployed :tada:

**Pull request merged**
