### PR TITLE
Duplicate key for property path #11

### PR DESCRIPTION
**Pull request by pmiguelmartins**
Insert params in context and meta when creating pages.

Need some improvements but its working

### CODE REVIEW

**Comment by daaru00** [comment]
Sorry I cannot understand which parts fix the issue.. seems you also remove the generation of default language, is related with the issue?

Can you explain the query variables page check that you perform? Seems in some case the locale context property will be not set.

**Comment by pmiguelmartins** [comment]
Hi, 
The problem I had was when generating the blog post that they where duplicated in internal count when creatingPage ... (that I check if is a template : check in queryString var.

The other problem was when I had a template like this ( /blog/:id ) the create gives a error saying that the :id wasn't found

So my idea was detect when the path was parameters I suppose that is a template and in that case I try to extract and add then in the create

I know that probably was not the best way ... but as I say I'm using this solution in production and is working

Sorry for the disturb if you want I can delete the pull request

**Comment by daaru00** [comment]
Ok, so basically you skip the default context locale property for template page, if I understand well. If you try to access `$context.locale` it is undefined right?
I something that I thinking about, maybe a change like this can break some page query that have to access the locale to query content (common pattern for headless CMS for example).

I also open an issue to Gridsome core to ask for an API to edit pages: https://github.com/gridsome/gridsome/issues/1139 to directly delegate the "is a template" check to the core.

No disturbance, on the contrary it gives more information on where the error can be found. Can you please dry the solution of this check? in order to not conflicts with PR #9 #12 that made change some change in this context.

**Comment by pmiguelmartins** [comment]
Yes I check if is a template and Work other way...

“ No disturbance, on the contrary it gives more information on where the error can be found. Can you please dry the solution of this check? in order to not conflicts with PR #9 #12 that made change some change in this context. “

What you mean ? ... I’m Portuguese and my English is not the best...

PS - you can check this website Its working with this soluction on http://www.4p2p.pt/portefolio  even when you chance language Insider the post

**Comment by daaru00** [comment]
I close since the problem should be solved from version 1.5.0, thank you for the support!

**Pull request closed without merging**
