### PR TITLE
Feature/localized routes

### PR DESCRIPTION
**Pull request by giuseppeaiello**
Adds the option to generate customized translated routes.

### CODE REVIEW

**Comment by daaru00** [comment]
Hi @giuseppeaiello,

I really appreciate the routes generation switch off, thank you! 

I'm not entirely convinced whether to generate the pages directly inside the plugin or leave the user doing it by itself in his own `gridsome.server.js`. 

We have to maintain generation page options when Gridsome adds a new setting to the pages. What about let the user to valorize the entire page payloads? Something like this:
```js
this.options.routes.forEach(route => {
  createPage(route);
})
```
just thinking about if user what to set additional context variable or route meta.

If we let the user manage this part in the `gridsome.server.js` will have the freedom to generate pages loading the entire routing from an external source (like Storyblok/WordPress). If you need to make an HTTP call before generating the routes It would be impossible to do in `gridsome.config.js`.

What do you think about this?

**Comment by giuseppeaiello** [comment]
Hi @daaru00 ,
  I agree with you. I just noticed one thing: it's important to set the **route.meta.locale** property correctly for each route; I would avoid the user to have to dig into these logics but, at the same time, we can allow the possibility to manage it if needed. What do you think about having this in the gridsome.server.js plugin file?

```js
// Create custom localized routes using the this.options.routes object
if (this.options.routes) {

  this.options.routes.forEach(customRoute => {

    // Assign the meta.locale - if empty - property automatically using the context.locale
    if (customRoute.route === undefined) {
      customRoute.route = {
        meta: {
          locale: customRoute.context.locale
        }
      };
    }

    createPage(customRoute);
  })
      
}

// Disallow the automatic creation of the localized routes
if (this.options.enablePathGeneration === false) return;
```

**Comment by daaru00** [comment]
Yep, it sound good! I could also advise setting the context `locale` property in order to use that parameter in GraphQL queries.

Can you please add an example configuration how to set translated routes? I think it got lost between one PR and an other.

Just a note, you should check for specific locale meta:
```js
customRoute.route = customRoute.route || {}
customRoute.route.meta = customRoute.route.meta || {}

if (customRoute.route.meta.locale === undefined) {
    customRoute.route.meta.locale = customRoute.context.locale || this.options.defaultLocale // just in case also context has no locale
}
```
this in order to set locale property even if an other route meta is set and leaves original meta intact.

What about if routes are nested directly in a locale configuration? Something like Nuxt do: https://i18n.nuxtjs.org/routing.html#custom-paths. In this case it is always possible to understand what language the route has:
```js
options.locales.forEach(locale => {
  const routes = this.options.routes[locale]
  if (!routes) {
    return
  }

  routes.forEach(customRoute => {

    customRoute.route = customRoute.route || {}
    customRoute.route.meta = customRoute.route.meta || {}
    customRoute.route.meta.locale = locale // directly set locale value

    customRoute.context = customRoute.context || {}
    customRoute.context.locale = locale // directly set locale value

    createPage(customRoute);
  })

})
```
this removes the need to check the meta and context values to set it.

**Comment by giuseppeaiello** [comment]
ok. This in the **gridsome.server.js** of the plugin:
```js
// Create custom localized routes
    this.options.locales.forEach(locale => {
      const routes = this.options.routes[locale]
      if (!routes) {
        return
      }
      
      routes.forEach(customRoute => {
        customRoute.route = customRoute.route || {}
        customRoute.route.meta = customRoute.route.meta || {}
        customRoute.route.meta.locale = locale
    
        customRoute.context = customRoute.context || {}
        customRoute.context.locale = locale
    
        createPage(customRoute);
      })
    
    })
```

with the following routes definition in **routes.js** of the project:
```js
module.exports = {
    en: [
      {
        path: '/en/',
        component: './src/pages/Index.vue',
        context: {
          slug: '/'
        }
      },
      {
        path: '/en/about/',
        component: './src/pages/About.vue',
        context: {
          slug: '/about'
        }
      }
  ],
  it: [
      {
        path: '/',
        component: './src/pages/Index.vue',
        context: {
          slug: '/'
        }
      },
      {
        path: '/it/chi-siamo/',
        component: './src/pages/About.vue',
        context: {
          slug: '/about'
        }
      }
    ]
}
```
seems to work correctly 👍🏼

Is this what you were thinking about @daaru00 ?

**Review by daaru00 — APPROVED** [review]
Yess, I like it! Being an optional configuration and the additional logic is activated only conditionally I don't see any regression problems.

I'll merge your PR, add some doc about what we discussed and I plan the release :+1: 

Thank you very much for your contribution!

**Comment by daaru00** [comment]
Just added a little fix when creating documentation about different configurations options:

If `routes` options is not set the default value is `null`, so it raise an error during locale routes lookup:
```
TypeError: Cannot read property 'en' of null
    at options.locales.forEach.locale (/home/user/gridsome-plugin-i18n/gridsome.server.js:47:43)
    at Array.forEach (<anonymous>)
    at VueI18n.createManagedPages (/home/user/gridsome-plugin-i18n/gridsome.server.js:46:28)
    at Plugins.run (/home/user/test/node_modules/gridsome/lib/app/Plugins.js:141:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
change the default value to en empty object it solve the issue: https://github.com/daaru00/gridsome-plugin-i18n/commit/94f33604878702f9a6c26d761516997d07c180be

**Comment by dcruz1990** [comment]
I'm trying to do the same thing but can't figure where to put the page generation code?

**Pull request merged**
